export const day = {
  'Sunny': './weather-icons/clear-day.svg' ,
  'Partly cloudy': './weather-icons/partly-cloudy-day.svg',
  'Cloudy': './weather-icons/cloudy.svg',
  'Overcast': './weather-icons/overcast.svg',
  'Patchy rain possible': './weather-icons/overcast-day-drizzle.svg',
  'Mist': './weather-icons/mist.svg',
  'Patchy snow possible': './weather-icons/overcast-day-snow.svg',
  'Patchy sleet possible': './weather-icons/overcast-day-sleet.svg',
  'Patchy freezing drizzle possible': './weather-icons/overcast-night-hail.svg',
  'Thundery outbreaks possible': './weather-icons/thunderstorms-day.svg',
  'Blowing snow': './weather-icons/wind-snow.svg',
  'Blizzard': './weather-icons/extreme-snow.svg',
  'Fog': './weather-icons/fog.svg',
  'Freezing fog': './weather-icons/fog.svg',
  'Patchy light drizzle': './weather-icons/partly-cloudy-day-drizzle.svg',
  'Light drizzle': './weather-icons/drizzle.svg',
  'Freezing drizzle': './weather-icons/overcast-hail.svg',
  'Heavy freezing drizzle': './weather-icons/extreme-hail.svg',
  'Patchy light rain': './weather-icons/partly-cloudy-day-rain.svg',
  'Light rain': './weather-icons/overcast-day-rain.svg',
  'Moderate rain': './weather-icons/rain.svg',
  'Heavy rain': './weather-icons/extreme-rain.svg',
  'Heavy rain at times': './weather-icons/extreme-day-rain.svg',
  'Moderate rain at times': './weather-icons/partly-cloudy-day-rain.svg',
  'Light freezing rain': './weather-icons/overcast-hail.svg',
  'Moderate or heavy freezing rain': './weather-icons/extreme-hail.svg',
  'Light sleet': './weather-icons/overcast-sleet.svg',
  'Moderate or heavy sleet': './weather-icons/extreme-sleet.svg',
  'Patchy light snow': './weather-icons/partly-cloudy-day-snow.svg',
  'Light snow': './weather-icons/overcast-snow.svg',
  'Heavy snow': './weather-icons/extreme-snow.svg',
  'Moderate snow': './weather-icons/snow.svg',
  'Patchy moderate snow': './weather-icons/partly-cloudy-day-snow.svg',
  'Patchy heavy snow': './weather-icons/extreme-day-snow.svg',
  'Ice pellets': './weather-icons/hail.svg',
  'Light rain shower': './weather-icons/partly-cloudy-day-rain.svg',
  'Moderate or heavy rain shower': './weather-icons/extreme-day-rain.svg',
  'Torrential rain shower': './weather-icons/extreme-day-rain.svg',
  'Light sleet showers': './weather-icons/partly-cloudy-day-sleet.svg',
  'Moderate or heavy sleet showers': './weather-icons/extreme-day-sleet.svg',
  'Light snow showers': './weather-icons/partly-cloudy-day-snow.svg',
  'Moderate or heavy snow showers': './weather-icons/extreme-day-snow.svg',
  'Light showers of ice pellets': './weather-icons/partly-cloudy-day-hail.svg',
  'Moderate or heavy showers of ice pellets': './weather-icons/extreme-day-hail.svg',
  'Patchy light rain with thunder': './weather-icons/thunderstorms-day-rain.svg',
  'Patchy light snow with thunder': './weather-icons/thunderstorms-day-snow.svg',
  'Moderate or heavy snow with thunder': './weather-icons/thunderstorms-extreme-snow.svg',
  'Moderate or heavy rain with thunder': './weather-icons/thunderstorms-extreme-rain.svg'
}

export const night = {
  'Clear': './weather-icons/clear-night.svg',
  'Partly cloudy': './weather-icons/partly-cloudy-night.svg',
  'Cloudy': './weather-icons/cloudy.svg',
  'Overcast': './weather-icons/overcast.svg',
  'Patchy rain possible': './weather-icons/overcast-night-drizzle.svg',
  'Mist': './weather-icons/mist.svg',
  'Patchy snow possible': './weather-icons/overcast-night-snow.svg',
  'Patchy sleet possible': './weather-icons/overcast-night-sleet.svg',
  'Patchy freezing drizzle possible': './weather-icons/overcast-night-hail.svg',
  'Thundery outbreaks possible': './weather-icons/thunderstorms-night.svg',
  'Blowing snow': './weather-icons/wind-snow.svg',
  'Blizzard': './weather-icons/extreme-snow.svg',
  'Fog': './weather-icons/fog.svg',
  'Freezing fog': './weather-icons/fog.svg',
  'Patchy light drizzle': './weather-icons/partly-cloudy-night-drizzle.svg',
  'Light drizzle': './weather-icons/drizzle.svg',
  'Freezing drizzle': './weather-icons/overcast-hail.svg',
  'Heavy freezing drizzle': './weather-icons/extreme-hail.svg',
  'Patchy light rain': './weather-icons/partly-cloudy-night-rain.svg',
  'Light rain': './weather-icons/overcast-night-rain.svg',
  'Moderate rain': './weather-icons/rain.svg',
  'Heavy rain': './weather-icons/extreme-rain.svg',
  'Heavy rain at times': './weather-icons/extreme-night-rain.svg',
  'Moderate rain at times': './weather-icons/partly-cloudy-night-rain.svg',
  'Light freezing rain': './weather-icons/overcast-hail.svg',
  'Moderate or heavy freezing rain': './weather-icons/extreme-hail.svg',
  'Light sleet': './weather-icons/overcast-sleet.svg',
  'Moderate or heavy sleet': './weather-icons/extreme-sleet.svg',
  'Patchy light snow': './weather-icons/partly-cloudy-night-snow.svg',
  'Light snow': './weather-icons/overcast-snow.svg',
  'Heavy snow': './weather-icons/extreme-snow.svg',
  'Moderate snow': './weather-icons/snow.svg',
  'Patchy moderate snow': './weather-icons/partly-cloudy-night-snow.svg',
  'Patchy heavy snow': './weather-icons/extreme-night-snow.svg',
  'Ice pellets': './weather-icons/hail.svg',
  'Light rain shower': './weather-icons/partly-cloudy-night-rain.svg',
  'Moderate or heavy rain shower': './weather-icons/extreme-night-rain.svg',
  'Torrential rain shower': './weather-icons/extreme-night-rain.svg',
  'Light sleet showers': './weather-icons/partly-cloudy-night-sleet.svg',
  'Moderate or heavy sleet showers': './weather-icons/extreme-night-sleet.svg',
  'Light snow showers': './weather-icons/partly-cloudy-night-snow.svg',
  'Moderate or heavy snow showers': './weather-icons/extreme-night-snow.svg',
  'Light showers of ice pellets': './weather-icons/partly-cloudy-night-hail.svg',
  'Moderate or heavy showers of ice pellets': './weather-icons/extreme-night-hail.svg',
  'Patchy light rain with thunder': './weather-icons/thunderstorms-night-rain.svg',
  'Patchy light snow with thunder': './weather-icons/thunderstorms-night-snow.svg',
  'Moderate or heavy snow with thunder': './weather-icons/thunderstorms-extreme-snow.svg',
  'Moderate or heavy rain with thunder': './weather-icons/thunderstorms-extreme-rain.svg'
}